# Generated by Django 5.0.6 on 2024-07-03 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hudud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Qurilish_tashkiloti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('qachon_tashkil_topgan', models.DateField()),
                ('hudud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qurilish.hudud')),
            ],
        ),
        migrations.CreateModel(
            name='Qurilish_binosi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('maydoni', models.PositiveIntegerField()),
                ('qavat', models.PositiveIntegerField()),
                ('porkovka', models.BooleanField(default=False)),
                ('bolalar_maydonchasi', models.BooleanField(default=False)),
                ('lift', models.BooleanField(default=False)),
                ('hudud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qurilish.hudud')),
                ('qurilish_tashkiloti', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qurilish.qurilish_tashkiloti')),
            ],
        ),
    ]
